# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Orthonormal basis decomposition.
#'
#' \code{E_coeff} computes the \eqn{d^2} real-valued basis coefficients with respect to an orthonormal
#' (in terms of the Frobenius metric) basis of the real vector space of \eqn{(d x d)}-dimensional
#' Hermitian matrices.
#'
#' @param H a \eqn{(d x d)}-dimensional Hermitian matrix.
#' @param E an array of orthonormal \eqn{(d x d)}-dimensional basis elements obtained by \code{E_basis(d)}.
#'
#' @examples
#'  E <- E_basis(3)
#'  h <- matrix(complex(real = rnorm(9), imaginary = rnorm(9)), nrow = 3)
#'  H <- t(Conj(h)) %*% h
#'  E_coeff(H, E)
#'
#' @seealso \code{\link{E_coeff_inv}}, \code{\link{E_basis}}
#'
#' @export
E_coeff <- function(H, E) {
    .Call('pdSpecEst_E_coeff', PACKAGE = 'pdSpecEst', H, E)
}

#' Orthonormal basis recomposition.
#'
#' \code{E_coeff_inv} computes the \eqn{(d x d)}-dimensional Hermitian matrix with (real-valued) coefficients
#' \code{coeff} in the orthonormal basis \code{E_basis(d)}.
#'
#' @param coeff  a numeric vector.
#' @param E  an array of orthonormal basis elements obtained by \code{E_basis(d)}.
#'
#' @examples
#'  E <- E_basis(3)
#'  coeff <- rnorm(9)
#'  E_coeff_inv(coeff, E)
#'
#' @seealso \code{\link{E_coeff}}, \code{\link{E_basis}}
#'
#' @export
E_coeff_inv <- function(coeff, E) {
    .Call('pdSpecEst_E_coeff_inv', PACKAGE = 'pdSpecEst', coeff, E)
}

#' Exponential map.
#'
#' \code{Expm(P, H)} computes the projection of a Hermitian matrix \code{H} from the tangent space at a Hermitian
#' positive-definite matrix \code{P} to the Riemannian manifold of Hermitian PD matrices via the
#' exponential map as in (Pennec, 2006).
#'
#' @param P a square Hermitian positive-definite matrix.
#' @param H a square Hermitian matrix (of equal dimension as \code{P}).
#'
#' @examples
#'  H <- matrix(complex(real = rnorm(9), imaginary = rnorm(9)), nrow = 3)
#'  diag(H) <- rnorm(3)
#'  H[lower.tri(H)] <- t(Conj(H))[lower.tri(H)]
#'  p <- matrix(complex(real = rnorm(9), imaginary = rnorm(9)), nrow = 3)
#'  P <- t(Conj(p)) %*% p
#'  Expm(P, H)
#'
#' @references
#' Pennec, X. (2006). Intrinsic statistics on Riemannian manifolds: Basic tools for geometric
#' measurements. \emph{Journal of Mathematical Imaging and Vision} 25(1), 127-154.
#'
#' @seealso \code{\link{Logm}}
#'
#' @export
Expm <- function(P, H) {
    .Call('pdSpecEst_Expm', PACKAGE = 'pdSpecEst', P, H)
}

#' Logarithmic map.
#'
#' \code{Logm(P, Q)} computes the projection of the HPD-matrix \code{Q} on the Riemannian manifold to
#' the tangent space attached at the HPD-matrix \code{P} via the logarithmic map as in (Pennec, 2006).
#'
#' @param P a square HPD-matrix.
#' @param Q a square HPD-matrix (of equal dimension as \code{P}).
#'
#' @examples
#'  q <- matrix(complex(real = rnorm(9), imaginary = rnorm(9)), nrow = 3)
#'  Q <- t(Conj(q)) %*% q
#'  p <- matrix(complex(real = rnorm(9), imaginary = rnorm(9)), nrow = 3)
#'  P <- t(Conj(p)) %*% p
#'  Logm(P, Q)
#'
#' @references
#' Pennec, X. (2006). Intrinsic statistics on Riemannian manifolds: Basic tools for geometric
#' measurements. \emph{Journal of Mathematical Imaging and Vision} 25(1), 127-154.
#'
#' @seealso \code{\link{Expm}}
#'
#' @export
Logm <- function(P, Q) {
    .Call('pdSpecEst_Logm', PACKAGE = 'pdSpecEst', P, Q)
}

#' @export
Mid <- function(A, B) {
    .Call('pdSpecEst_Mid', PACKAGE = 'pdSpecEst', A, B)
}

#' @export
NormF <- function(M) {
    .Call('pdSpecEst_NormF', PACKAGE = 'pdSpecEst', M)
}

#' Riemannian distance HPD-matrices.
#'
#' \code{RiemmDist} calculates the natural Riemannian distance between two Hermitian, positive-definite matrices as
#' in (Bhatia, 2009, Chapter 6).
#'
#'
#' @param A,B Hermitian, positive-definite matrices (of equal dimension).
#'
#' @examples
#'  a <- matrix(complex(real = rnorm(9), imaginary = rnorm(9)), nrow = 3)
#'  A <- t(Conj(a)) %*% a
#'  b <- matrix(complex(real = rnorm(9), imaginary = rnorm(9)), nrow = 3)
#'  B <- t(Conj(b)) %*% b
#'  RiemmDist(A, B)
#' @references Bhatia, R. (2009). \emph{Positive Definite Matrices}. New Jersey: Princeton University Press.
#'
#' @export
RiemmDist <- function(A, B) {
    .Call('pdSpecEst_RiemmDist', PACKAGE = 'pdSpecEst', A, B)
}

#' @export
solveMid <- function(B, C) {
    .Call('pdSpecEst_solveMid', PACKAGE = 'pdSpecEst', B, C)
}

#' @export
Sqrt <- function(M) {
    .Call('pdSpecEst_Sqrt', PACKAGE = 'pdSpecEst', M)
}

#' @export
iSqrt <- function(M) {
    .Call('pdSpecEst_iSqrt', PACKAGE = 'pdSpecEst', M)
}

#' @export
kMean <- function(M, mu) {
    .Call('pdSpecEst_kMean', PACKAGE = 'pdSpecEst', M, mu)
}

